import AppKit
import Foundation
import Observation

// MARK: - SetupTerminalApp

enum SetupTerminalApp: String, CaseIterable, Identifiable {
    case appleTerminal
    case iTerm2
    case ghostty
    case custom

    // MARK: Internal

    var id: String {
        rawValue
    }

    var title: String {
        switch self {
        case .appleTerminal:
            String(localized: "Apple Terminal")
        case .iTerm2:
            String(localized: "iTerm2")
        case .ghostty:
            String(localized: "Ghostty")
        case .custom:
            String(localized: "My own Terminal...")
        }
    }
}

// MARK: - SetupBrowserApp

enum SetupBrowserApp: String, CaseIterable, Identifiable {
    case chromeNewProfile
    case chromeCurrentProfile
    case firefox
    case braveComingSoon

    // MARK: Internal

    var id: String {
        rawValue
    }

    var title: String {
        switch self {
        case .chromeNewProfile:
            String(localized: "Google Chrome (New Profile)...")
        case .chromeCurrentProfile:
            String(localized: "Google Chrome (Current Profile)...")
        case .firefox:
            String(localized: "Firefox...")
        case .braveComingSoon:
            String(localized: "Brave (coming soon)")
        }
    }

    var isEnabled: Bool {
        self != .braveComingSoon
    }
}

// MARK: - RockxySetupScriptContext

struct RockxySetupScriptContext: Equatable {
    let proxyHost: String
    let proxyPort: Int
    let certificatePath: String?
    let generatedAt: Date
    let appName: String
}

// MARK: - RockxySetupScriptBuilder

enum RockxySetupScriptBuilder {
    static let relativeScriptPath = "setup/rockxy_env_setup.sh"

    static func generatedScriptURL(
        identity: RockxyIdentity = .current,
        fileManager: FileManager = .default
    ) -> URL {
        identity.appSupportPath(relativeScriptPath, fileManager: fileManager)
    }

    static func sourceCommand(scriptURL: URL) -> String {
        let quotedPath = shellDoubleQuoted(scriptURL.path)
        return "set -a 2>/dev/null || true; source \(quotedPath); set +a 2>/dev/null || true"
    }

    @discardableResult
    static func writeScript(
        context: RockxySetupScriptContext,
        scriptURL: URL = generatedScriptURL(),
        fileManager: FileManager = .default
    ) throws -> URL {
        let directory = scriptURL.deletingLastPathComponent()
        try fileManager.createDirectory(at: directory, withIntermediateDirectories: true)

        let contents = script(context: context)
        let temporaryURL = directory
            .appendingPathComponent(".\(scriptURL.lastPathComponent).tmp-\(UUID().uuidString)")
        try contents.write(to: temporaryURL, atomically: true, encoding: .utf8)
        try fileManager.setAttributes([.posixPermissions: 0o700], ofItemAtPath: temporaryURL.path)

        if fileManager.fileExists(atPath: scriptURL.path) {
            _ = try fileManager.replaceItemAt(scriptURL, withItemAt: temporaryURL)
        } else {
            try fileManager.moveItem(at: temporaryURL, to: scriptURL)
        }

        try fileManager.setAttributes([.posixPermissions: 0o700], ofItemAtPath: scriptURL.path)
        return scriptURL
    }

    static func script(context: RockxySetupScriptContext) -> String {
        let proxyURL = "http://\(context.proxyHost):\(context.proxyPort)"
        let generatedAt = ISO8601DateFormatter().string(from: context.generatedAt)
        var lines = [
            "#!/bin/zsh",
            "# Generated by \(context.appName). Do not edit this file directly.",
            "# Rockxy setup script version: 1",
            "# Generated at: \(generatedAt)",
            "",
            "export ROCKXY_SETUP_SESSION=1",
            "export ROCKXY_PROXY_HOST=\(shellDoubleQuoted(context.proxyHost))",
            "export ROCKXY_PROXY_PORT=\(shellDoubleQuoted(String(context.proxyPort)))",
            "export HTTP_PROXY=\(shellDoubleQuoted(proxyURL))",
            "export HTTPS_PROXY=\(shellDoubleQuoted(proxyURL))",
            "export ALL_PROXY=\(shellDoubleQuoted(proxyURL))",
            "export http_proxy=\"$HTTP_PROXY\"",
            "export https_proxy=\"$HTTPS_PROXY\"",
            "export all_proxy=\"$ALL_PROXY\"",
            "export NO_PROXY=\"${NO_PROXY:-localhost,127.0.0.1,::1}\"",
            "export no_proxy=\"$NO_PROXY\"",
        ]

        if let certificatePath = context.certificatePath, !certificatePath.isEmpty {
            lines.append(contentsOf: [
                "export ROCKXY_ROOT_CA_PATH=\(shellDoubleQuoted(certificatePath))",
                "export SSL_CERT_FILE=\"$ROCKXY_ROOT_CA_PATH\"",
                "export REQUESTS_CA_BUNDLE=\"$ROCKXY_ROOT_CA_PATH\"",
                "export NODE_EXTRA_CA_CERTS=\"$ROCKXY_ROOT_CA_PATH\"",
                "case \" ${NODE_OPTIONS:-} \" in",
                "  *\" --use-openssl-ca \"*) ;;",
                "  *) export NODE_OPTIONS=\"${NODE_OPTIONS:-} --use-openssl-ca\" ;;",
                "esac",
            ])
        } else {
            lines.append("# Export or trust the Rockxy root certificate to enable certificate environment hints.")
        }

        lines.append(contentsOf: [
            "",
            "echo \"\(context.appName) setup session is ready: $HTTP_PROXY\"",
            "echo \"Run your server or script in this terminal so Rockxy can capture its HTTP and HTTPS traffic.\"",
            "",
        ])

        return lines.joined(separator: "\n")
    }

    static func shellSingleQuoted(_ value: String) -> String {
        "'\(value.replacingOccurrences(of: "'", with: "'\"'\"'"))'"
    }

    static func shellDoubleQuoted(_ value: String) -> String {
        "\"\(value.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\""))\""
    }
}

// MARK: - RockxySetupSessionLauncher

enum RockxySetupSessionLauncher {
    static func openTerminal(_ app: SetupTerminalApp, sourceCommand: String) throws {
        let command = "\(sourceCommand) && printf '\\nRockxy is ready. Start your server or scripts here.\\n'"

        switch app {
        case .appleTerminal:
            try runAppleScript("""
            tell application "Terminal"
                activate
                do script "\(appleScriptString(command))"
            end tell
            """)
        case .iTerm2:
            try runAppleScript("""
            tell application "iTerm2"
                activate
                create window with default profile
                tell current session of current window
                    write text "\(appleScriptString(command))"
                end tell
            end tell
            """)
        case .ghostty:
            try runProcess(
                executable: "/usr/bin/open",
                arguments: ["-na", "Ghostty", "--args", "-e", "/bin/zsh", "-lc", "\(command); exec /bin/zsh -l"]
            )
        case .custom:
            NSPasteboard.general.clearContents()
            NSPasteboard.general.setString(sourceCommand, forType: .string)
        }
    }

    static func openBrowser(
        _ app: SetupBrowserApp,
        proxyHost: String,
        proxyPort: Int,
        supportDirectory: URL = RockxyIdentity.current.appSupportPath("setup")
    ) throws {
        guard app.isEnabled else {
            return
        }

        let proxyServer = "http://\(proxyHost):\(proxyPort)"
        switch app {
        case .chromeNewProfile:
            let profileURL = supportDirectory.appendingPathComponent("Chrome Profile", isDirectory: true)
            try FileManager.default.createDirectory(at: profileURL, withIntermediateDirectories: true)
            try runProcess(
                executable: "/usr/bin/open",
                arguments: [
                    "-na", "Google Chrome", "--args",
                    "--user-data-dir=\(profileURL.path)",
                    "--proxy-server=\(proxyServer)",
                    "--proxy-bypass-list=<-loopback>",
                ]
            )
        case .chromeCurrentProfile:
            try runProcess(
                executable: "/usr/bin/open",
                arguments: ["-a", "Google Chrome", "--args", "--proxy-server=\(proxyServer)"]
            )
        case .firefox:
            let profileURL = supportDirectory.appendingPathComponent("Firefox Profile", isDirectory: true)
            try FileManager.default.createDirectory(at: profileURL, withIntermediateDirectories: true)
            try firefoxUserJS(proxyHost: proxyHost, proxyPort: proxyPort)
                .write(to: profileURL.appendingPathComponent("user.js"), atomically: true, encoding: .utf8)
            try runProcess(
                executable: "/usr/bin/open",
                arguments: ["-na", "Firefox", "--args", "-no-remote", "-profile", profileURL.path]
            )
        case .braveComingSoon:
            return
        }
    }

    static func firefoxUserJS(proxyHost: String, proxyPort: Int) -> String {
        """
        user_pref("network.proxy.type", 1);
        user_pref("network.proxy.http", "\(proxyHost)");
        user_pref("network.proxy.http_port", \(proxyPort));
        user_pref("network.proxy.ssl", "\(proxyHost)");
        user_pref("network.proxy.ssl_port", \(proxyPort));
        user_pref("network.proxy.no_proxies_on", "localhost, 127.0.0.1, ::1");
        """
    }

    // MARK: Private

    private static func runAppleScript(_ script: String) throws {
        try runProcess(executable: "/usr/bin/osascript", arguments: ["-e", script])
    }

    private static func runProcess(executable: String, arguments: [String]) throws {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: executable)
        process.arguments = arguments
        process.standardOutput = Pipe()
        process.standardError = Pipe()
        try process.run()
    }

    private static func appleScriptString(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
    }
}

// MARK: - DeveloperSetupSessionSetupViewModel

@MainActor @Observable
final class DeveloperSetupSessionSetupViewModel {
    // MARK: Lifecycle

    init(coordinator: MainContentCoordinator, generatedAt: @escaping () -> Date = Date.init) {
        self.coordinator = coordinator
        self.generatedAt = generatedAt
        context = Self.makeContext(coordinator: coordinator, generatedAt: generatedAt())
    }

    // MARK: Internal

    var selectedTerminalApp: SetupTerminalApp = .appleTerminal
    var selectedBrowserApp: SetupBrowserApp = .chromeNewProfile
    var statusMessage: String?
    var context: RockxySetupScriptContext

    var scriptURL: URL {
        RockxySetupScriptBuilder.generatedScriptURL()
    }

    var manualSourceCommand: String {
        RockxySetupScriptBuilder.sourceCommand(scriptURL: scriptURL)
    }

    var proxyEndpointText: String {
        "\(context.proxyHost):\(context.proxyPort)"
    }

    var certificateStatusText: String {
        if context.certificatePath != nil {
            return String(localized: "Certificate environment hints are ready.")
        }
        return String(localized: "Export the Rockxy root certificate to add certificate environment hints.")
    }

    func refresh() {
        context = Self.makeContext(coordinator: coordinator, generatedAt: generatedAt())
    }

    func prepareScript() throws {
        refresh()
        try RockxySetupScriptBuilder.writeScript(context: context, scriptURL: scriptURL)
    }

    func prepareScriptForDisplay() {
        do {
            try prepareScript()
            statusMessage = String(localized: "Setup script is ready.")
        } catch {
            statusMessage = String(localized: "Could not prepare the setup script: \(error.localizedDescription)")
        }
    }

    func copyManualCommand() {
        do {
            try prepareScript()
            NSPasteboard.general.clearContents()
            NSPasteboard.general.setString(manualSourceCommand, forType: .string)
            statusMessage = String(localized: "Manual Setup command copied.")
        } catch {
            statusMessage = String(localized: "Could not prepare the setup script: \(error.localizedDescription)")
        }
    }

    func openPreparedTerminal() {
        do {
            try prepareScript()
            try RockxySetupSessionLauncher.openTerminal(selectedTerminalApp, sourceCommand: manualSourceCommand)
            statusMessage = selectedTerminalApp == .custom
                ? String(localized: "Setup command copied. Paste it into your terminal.")
                : String(localized: "Prepared terminal session opened.")
        } catch {
            statusMessage = String(localized: "Could not open the prepared terminal: \(error.localizedDescription)")
        }
    }

    func openPreparedBrowser() {
        do {
            try prepareScript()
            try RockxySetupSessionLauncher.openBrowser(
                selectedBrowserApp,
                proxyHost: context.proxyHost,
                proxyPort: context.proxyPort
            )
            statusMessage = String(localized: "Prepared browser profile opened.")
        } catch {
            statusMessage = String(localized: "Could not open the prepared browser: \(error.localizedDescription)")
        }
    }

    static func makeContext(coordinator: MainContentCoordinator, generatedAt: Date) -> RockxySetupScriptContext {
        let settings = AppSettingsManager.shared.settings
        let port = DeveloperSetupViewModel.resolveSnippetPort(
            isProxyRunning: coordinator.isProxyRunning,
            activePort: coordinator.activeProxyPort,
            configuredPort: settings.proxyPort
        )
        let certificatePath = settings.lastExportedRootCAPath.flatMap { path -> String? in
            FileManager.default.fileExists(atPath: path) ? path : nil
        }

        return RockxySetupScriptContext(
            proxyHost: "127.0.0.1",
            proxyPort: port,
            certificatePath: certificatePath,
            generatedAt: generatedAt,
            appName: RockxyIdentity.current.displayName
        )
    }

    // MARK: Private

    private let coordinator: MainContentCoordinator
    private let generatedAt: () -> Date
}
